package com.example.symptomatch;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

public class ConditionInfoActivity extends AppCompatActivity {

    private DatabaseHelper db;
    private Condition condition;
    private String passedName;
    private TextView name;
    private TextView disclaimer;
    private TextView symptoms;
    private TextView description;
    private TextView treatments;
    private TextView actions;
    private Button saveButton;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_condition_info);

        name = (TextView) findViewById(R.id.conditionNameTextView);
        disclaimer = (TextView) findViewById(R.id.conditionDisclaimerTextView);
        symptoms = (TextView) findViewById(R.id.conditionSymptomsBodyTextView);
        description = (TextView) findViewById(R.id.conditionDescriptionBodyTextView);
        treatments = (TextView) findViewById(R.id.conditionTreatmentsBodyTextView);
        actions = (TextView) findViewById(R.id.conditionRecActionsBodyTextView);
        saveButton = (Button) findViewById(R.id.saveConditionButton);

        Intent intent = getIntent();
        passedName = intent.getStringExtra("name");

        db = new DatabaseHelper(this);
        condition = db.getCondition(passedName);
        name.setText(condition.getName());
        disclaimer.setText("DISCLAIMER: The following results were generated by ChatGPT by using the following webpage:\n\n" + condition.getUrl() + "\n\nIf you think you may need medical help, seek a medical professional.");
        symptoms.setText(condition.getSymptoms());
        description.setText(condition.getDescription());
        treatments.setText(condition.getTreatments());
        actions.setText(condition.getActions());
        if (condition.isSaved())
            saveButton.setText(R.string.condition_info_save_btn_remove);
        else
            saveButton.setText(R.string.condition_info_save_btn_save);
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        db.close();
    }

    public void SaveConditionButtonClicked(View view)
    {
        if (condition.isSaved()) {
            condition.setSaved(0);
            db.updateCondition(condition);
            saveButton.setText(R.string.condition_info_save_btn_save);
            Toast.makeText(this, "Condition Removed", Toast.LENGTH_SHORT).show();
        }
        else {
            condition.setSaved(1);
            db.updateCondition(condition);
            saveButton.setText(R.string.condition_info_save_btn_remove);
        }
    }
}